#!/bin/bash -e

DIR="$(pwd)"

docker run --rm -it \
  -w "$DIR" \
  -v "$DIR:$DIR" \
  -v "$HOME/.claude:/root/.claude" \
  -v "$HOME/.claude.json:/root/.claude.json" \
  autonomouslogic/claude-container:latest \
  "$@"
