name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Build Docker image
        run: docker build --pull --tag autonomouslogic/claude-container:dev -f Dockerfile .

      - name: Check Claude Code version
        run: docker run --rm autonomouslogic/claude-container:dev --version
